apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  labels:
    app: test-deploy
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1730998702765
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
        - name: test-deploy
          image: acrdebu.azurecr.io/image-workflow-1730998702765:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
