apiVersion: v1
kind: Service
metadata:
  name: test-deploy
  namespace: namespace-workflow-1730998702765
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: test-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80