apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy234
  labels:
    app: test-deploy234
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1734377872791
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deploy234
  template:
    metadata:
      labels:
        app: test-deploy234
    spec:
      containers:
        - name: test-deploy234
          image: acrdemo2.azurecr.io/image-workflow-1734377872791:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
