apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotary-1
  labels:
    app: rotary-1
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1731521786781
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rotary-1
  template:
    metadata:
      labels:
        app: rotary-1
    spec:
      containers:
        - name: rotary-1
          image: rotaryreg.azurecr.io/rortaryregimg:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80