apiVersion: v1
kind: Service
metadata:
  name: rotary-1
  namespace: namespace-workflow-1731521786781
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: rotary-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80