apiVersion: v1
kind: Service
metadata:
  name: aks-demo-vote
  namespace: default
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: aks-demo-vote
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000