apiVersion: v1
kind: Service
metadata:
  name: test-deploy234
  namespace: namespace-workflow-1734377872791
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: test-deploy234
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001