apiVersion: v1
kind: Service
metadata:
  name: demodevsecops1
  namespace: acrnamespace1
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: demodevsecops1
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001